name: tests

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
          - "windows-latest"
        php:
          - "7.3"
          - "7.4"
        dependencies:
          - "highest"
        laravel:
          - "8.x"
        minions:
          - "2.x"
        experimental:
          - false

    name: PHP${{ matrix.php }} with Laravel ${{ matrix.laravel }} and Minion ${{ matrix.minions }} on ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-${{ matrix.laravel }}-${{ matrix.minions }}-${{ matrix.php }}-${{ matrix.dependencies }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, sqlite3, pdo_sqlite, bcmath, fileinfo
          coverage: none

      - name: Install Laravel Framework ${{ matrix.laravel }}
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "katsana/minions:${{ matrix.minions }}" --no-interaction --no-update
      - name: Install dependencies
        uses: "ramsey/composer-install@v1"
      - name: Execute tests
        run: vendor/bin/phpunit
